import requests

# قائمة بـ WAFs المعروفة وطريقة اكتشافها
WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "cloudflare"],
        "response_code": [403, 503],
        "body": ["Cloudflare", "Attention Required!", "Checking your browser"]
    },
    "AWS WAF": {
        "headers": ["x-amz-cf-id", "x-amz-cf-pop"],
        "body": ["Request blocked", "AWS WAF"]
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "body": ["Sucuri WebSite Firewall", "Access Denied"]
    },
    "ModSecurity": {
        "headers": ["mod_security", "mod-security"],
        "body": ["ModSecurity", "Not Acceptable"]
    },
    "Akamai": {
        "headers": ["x-akamai-transformed", "x-akamai-request-id"],
        "body": ["Akamai Ghost", "Access Denied"]
    },
    "Imperva": {
        "headers": ["x-cdn", "x-iinfo"],
        "body": ["Imperva", "Incapsula"]
    },
    "Wordfence": {
        "headers": ["wordfence"],
        "body": ["Generated by Wordfence"]
    },
    "Barracuda": {
        "headers": ["barracuda"],
        "body": ["Barracuda", "Access Denied"]
    }
}


def detect_waf(url, timeout=10):
    """
    كشف إذا كان الموقع محمي بـ WAF
    """
    result = {
        "url": url,
        "has_waf": False,
        "waf_name": None,
        "confidence": "LOW",
        "evidence": []
    }
    
    try:
        # نرسل طلب عادي أولاً
        response = requests.get(url, timeout=timeout, verify=False, allow_redirects=True)
        result["status_code"] = response.status_code
        result["headers"] = dict(response.headers)
        
        # نبحث عن توقيعات WAF
        for waf_name, signatures in WAF_SIGNATURES.items():
            evidence = []
            
            # فحص الـ Headers
            for header in signatures.get("headers", []):
                for resp_header in response.headers:
                    if header.lower() in resp_header.lower():
                        evidence.append(f"Header: {resp_header}")
            
            # فحص الـ Response Body (أول 500 حرف فقط)
            body_lower = response.text[:500].lower()
            for body_sig in signatures.get("body", []):
                if body_sig.lower() in body_lower:
                    evidence.append(f"Body contains: {body_sig}")
            
            # فحص Status Code
            if response.status_code in signatures.get("response_code", []):
                evidence.append(f"Status code: {response.status_code}")
            
            if evidence:
                result["has_waf"] = True
                result["waf_name"] = waf_name
                result["evidence"] = evidence
                result["confidence"] = "HIGH" if len(evidence) >= 2 else "MEDIUM"
                break
        
        # لو مفيش WAF مكتشف
        if not result["has_waf"]:
            result["waf_name"] = "No WAF detected or unknown WAF"
            result["confidence"] = "LOW"
            
    except requests.exceptions.Timeout:
        result["error"] = "Timeout - Target may be blocking requests"
    except requests.exceptions.ConnectionError:
        result["error"] = "Connection error"
    except Exception as e:
        result["error"] = str(e)
    
    return result


def test_waf_by_payload(url, timeout=10):
    """
    اختبار WAF بإرسال payloads مشبوهة
    """
    payloads = [
        "' OR '1'='1",
        "<script>alert('xss')</script>",
        "../../../etc/passwd",
        "union select 1,2,3",
        "<?php system('id'); ?>"
    ]
    
    results = []
    for payload in payloads:
        try:
            test_url = f"{url}?test={payload}"
            response = requests.get(test_url, timeout=timeout, verify=False)
            
            if response.status_code in [403, 406, 429, 503]:
                results.append({
                    "payload": payload,
                    "blocked": True,
                    "status_code": response.status_code
                })
            else:
                results.append({
                    "payload": payload,
                    "blocked": False,
                    "status_code": response.status_code
                })
        except:
            results.append({
                "payload": payload,
                "blocked": True,
                "error": "Request failed"
            })
    
    return results
